### ISSUE TITLE
optional argument not passed correctly

### ISSUE THREAD

**Issue by codeprefect** [AlariCode/rabbitmq-rpc#1]
# Issue Description
I have a microservice with the following config
```[js]
{
      exchangeName,
      connections: [{
        login: this.envConfig.RABBITMQ_DEFAULT_USER,
        password: this.envConfig.RABBITMQ_DEFAULT_PASS,
        host: this.envConfig.RABBITMQ_DEFAULT_HOST,
      }],
      queueName: service ? service.queue : '',
      queueArguments: {
        durable: 'false',
      },
}
```

The queue overview page on the RabbitMQ UI is showing `durable: true` as found below

![Screenshot 2019-04-02 at 11 08 35 AM](https://user-images.githubusercontent.com/44836329/55394771-f09e9e00-5537-11e9-9dee-188271105496.png)

The connection went fine, but I desire that the queue durability be set as false.

Thank you.

**Comment by codeprefect** [comment]
After some little research, I realized that the error stems from here
```
export interface IRMQServiceOptions {
    exchangeName: string;
    connections: IRMQConnection[];
    queueName?: string;
    queueArguments?: {
        [key: string]: string;
    };
    prefetchCount?: number;
    isGlobalPrefetchCount?: boolean;
    reconnectTimeInSeconds?: number;
    messagesTimeout?: number;
    logMessages?: boolean;
}
```

I suggest the `queueArguments is changed to
```
queueArguments?: {
  [key: string]: string | boolean;
};
```
as anything apart from the boolean `false` evaluates to true at the other side.

**Comment by AlariCode** [comment]
@barakimam thank you for the suggestion! Durable is not queue argument, this is an additional parameter when you create queue or exchange:
![image](https://user-images.githubusercontent.com/2528600/55399542-0f129280-5554-11e9-9bdd-0777f98444f1.png)
To make this controllable, I added for you new options in version `0.7.9` (don't forget to update) with default `true`:

``` typescript
isQueueDurable?: boolean;
isExchangeDurable?: boolean;
```
So if you want to make not durable queue, just pass `isQueueDurable: false`. Would like to hear if it works for you!)

**Comment by AlariCode** [comment]
@barakimam closing issue, due to library update. Requested features added.
