### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by Mararok** [AlariCode/rabbitmq-rpc#3]
Can you add ssl connection support ?

**Comment by AlariCode** [comment]
@Mararok hello! This library is not in active support due to https://github.com/AlariCode/nestjs-rmq which is targeting NestJS. So adding SSL in not on roadmap. But it is with https://github.com/AlariCode/nestjs-rmq.

**Comment by Mararok** [comment]
Oh, yes I thought this library is dependency for your nestjs extension. I want use nestjs-rmq package, but I need secure connection for my application on production. I would be grateful if you can implement this in your nestjs lib 😍
